package API;

import java.io.*;
import java.time.LocalDate;
import java.util.ArrayList;

/**
 * Represents a vehicle in the rental system.
 * Manages the vehicle's characteristics, its availability status,
 * and maintains a history list of its rentals.
 * Implements the {@link History} and {@link ReadWriteCSV} interfaces.
 */
public class Car implements History, ReadWriteCSV {
    private static int counter = 1;

    /** Unique Identifier for the vehicle. */
    private final int id;

    // Vehicle characteristics
    private String plate;
    private String brand;
    private String type;
    private String model;
    private String year;
    private String color;

    /** Current status of the vehicle (AVAILABLE, RENTED). */
    private CarStatus carStatus;

    /** List containing the rental history specific to this vehicle. */
    ArrayList<Rental> carRentals;

    /**
     * Constructor for creating a NEW vehicle.
     * The ID is automatically generated by the system counter.
     *
     * @param plate License plate number.
     * @param brand Vehicle brand.
     * @param type  Vehicle type.
     * @param model Vehicle model.
     * @param year  Manufacturing year.
     * @param color Vehicle color.
     */
    public Car(String plate, String brand, String type, String model, String year, String color) {
        this.id = counter++;
        this.plate = plate;
        this.brand = brand;
        this.type = type;
        this.model = model;
        this.year = year;
        this.color = color;
        carStatus = CarStatus.AVAILABLE;
        carRentals = new ArrayList<>();
    }

    /**
     * Constructor for loading a vehicle from the csv file.
     * It updates the static counter to ensure unique IDs for future creations.
     *
     * @param id        Existing vehicle ID.
     * @param plate     License plate number.
     * @param brand     Vehicle brand.
     * @param type      Vehicle type.
     * @param model     Vehicle model.
     * @param year      Manufacturing year.
     * @param color     Vehicle color.
     * @param carStatus Current status.
     */
    public Car(int id, String plate, String brand, String type, String model, String year, String color, CarStatus carStatus) {
        this.id = id;
        this.plate = plate;
        this.brand = brand;
        this.type = type;
        this.model = model;
        this.year = year;
        this.color = color;
        this.carStatus = carStatus;
        carRentals = new ArrayList<>();

        if (id >= counter) {
            counter = id + 1;
        }
    }

    // --- GETTERS - SETTERS ---

    public int getId() {
        return id;
    }

    public String getPlate() {
        return plate;
    }

    public void setPlate(String plate) {
        this.plate = plate;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public CarStatus getCarStatus() {
        return carStatus;
    }

    public void setCarStatus(CarStatus carStatus) {
        this.carStatus = carStatus;
    }

    // --- LOGIC METHODS ---

    /**
     * Checks if the vehicle is currently available for rent.
     *
     * @return true if status is AVAILABLE, false otherwise.
     */
    public boolean isAvailable() {
        return this.carStatus == CarStatus.AVAILABLE;
    }

    /**
     * From interface History
     * Adds a rental record to the vehicle's history.
     * Checks for duplicate rental codes before adding.
     *
     * @param rental The rental object to add.
     * @return true if added successfully, false if a rental with the same code exists.
     */
    @Override
    public boolean addRental(Rental rental) {
        for (Rental r : carRentals) {
            if (r.getRentCode() == rental.getRentCode()) {
                System.out.println("Rental with code " + rental.getRentCode() + " already exists.");
                return false;
            }
        }
        carRentals.add(rental);
        return true;
    }

    /**
     * From interface History
     * Returns a defensive copy of the vehicle's rental history.
     *
     * @return An ArrayList containing the rental records.
     */
    @Override
    public ArrayList<Rental> returnList() {
        return new ArrayList<>(this.carRentals); // encapsulation - defensive copying
    }

    // --- CSV METHODS FOR HISTORY ---

    /**
     * From interface ReadWriteCSV
     * Reads the rental history from a CSV file.
     * Overrides the default method to filter only records matching this vehicle's plate.
     * Uses "d/M/yyyy" date format.
     *
     * @param CM       Car Manager instance.
     * @param CLM      Client Manager instance.
     * @param EM       Employee Manager instance.
     * @param filename Path to the CSV file.
     * @param list     (Ignored in this implementation, uses carRentals list).
     */
    @Override
    public void readCSV(CarManager CM, ClientManager CLM, EmployeeManager EM, String filename, ArrayList<Rental> list) {
        String line;
        String delimiter = ",";
        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("d/M/yyyy");

        try (BufferedReader in = new BufferedReader(new FileReader(filename))) {
            in.readLine();

            while ((line = in.readLine()) != null) {
                String[] data = line.split(delimiter);

                if (data.length >= 6) {
                    String plateRecord = data[1].trim();

                    // Load only if the record belongs to this car
                    if (plateRecord.equalsIgnoreCase(this.plate)) {
                        try {
                            int rentCode = Integer.parseInt(data[0].trim());
                            String afmClient = data[2].trim();

                            LocalDate start = LocalDate.parse(data[3].trim(), formatter);
                            LocalDate end = LocalDate.parse(data[4].trim(), formatter);

                            String userEmp = data[5].trim();

                            Client client = CLM.findByAFM(afmClient);
                            Employee employee = EM.findByUsername(userEmp);

                            if (client != null && employee != null) {
                                Rental rental = new Rental(rentCode, this, client, start, end, employee);
                                this.addRental(rental);
                            }
                        } catch (Exception e) {
                            System.out.println("Error parsing history line for car: " + this.plate);
                        }
                    }
                }
            }
        } catch (IOException e) {
            System.err.println("File not found: " + filename);
        }
    }

    /**
     * From interface ReadWriteCSV
     * Writes the vehicle's rental history to a CSV file.
     *
     * @param filename Path to the CSV file.
     * @param list     (Ignored, writes the carRentals list).
     */
    @Override
    public void writeCSV(String filename, ArrayList<Rental> list) {
        String line;
        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("d/M/yyyy");

        try (BufferedWriter out = new BufferedWriter(new FileWriter(filename))) {

            for (Rental rental : carRentals) {
                String sDate = rental.getStartDate().format(formatter);
                String eDate = rental.getEndDate().format(formatter);

                line = rental.getRentCode() + "," +
                        this.getPlate() + "," +
                        rental.getClient().getAFM() + "," +
                        sDate + "," +
                        eDate + "," +
                        rental.getEmployee().getUsername();

                out.write(line);
                out.newLine();
            }
        } catch (IOException e) {
            System.err.println("Error writing car history");
        }
    }

    // --- TO STRING ---

    @Override
    public String toString() {
        return "Car: " +
                "id=" + id +
                ", plate='" + plate + '\'' +
                ", brand='" + brand + '\'' +
                ", type='" + type + '\'' +
                ", model='" + model + '\'' +
                ", year='" + year + '\'' +
                ", color='" + color + '\'' +
                ", car status=" + carStatus;
    }
}